version: '3'
services:
  redis:
    image: redis:7.2.4
    container_name: test_inlaze
    ports:
      - '6379-6379'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
       - '3000:3000'
    depends_on:
      - redis
